[program:apache2]
command=/usr/sbin/apache2ctl -DFOREGROUND
process_name=%(program_name)s_%(process_num)s
autostart=true
autorestart=true
numprocs=1
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
